#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

ping_pong:
  path: /ping
  controller: App\Controller\Pong