App\Entity\MediaObject:
  iri: http://schema.org/MediaObject
  normalization_context: 'read:media_object'
  itemOperations:
    get: ~
  collectionOperations:
    get: ~
    post:
      controller: App\Controller\MediaObject\CreateMediaObjectController
      deserialize: false
      validation_groups: 
        - Default
        - create:media_object
      openapi_context:
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary